site_name: EXE CICD Exercise
site_url: https://exe.egger.codes
repo_url: https://github.com/MasonEgger-Demos/exe-cicd-exercise
repo_name: MasonEgger-Demos/exe-cicd-exercise
theme:
  name: material
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - toc:
      permalink: true
      toc_depth: 3
nav:
  - Home: index.md
  - Members:
      - Mason Egger: members/mason-egger.md
plugins:
  - search
